@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Mar 02 13:58:01 +0800 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto d0e08880f5e9435d88e97ce691d63dd9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot carry_lookahead_adder_16_bit_2_level_tb_behav xil_defaultlib.carry_lookahead_adder_16_bit_2_level_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto d0e08880f5e9435d88e97ce691d63dd9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot carry_lookahead_adder_16_bit_2_level_tb_behav xil_defaultlib.carry_lookahead_adder_16_bit_2_level_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
